### ISSUE TITLE
Publishing 1.0.2

### ISSUE THREAD

**Issue by robertjlooby** [elm-community/elm-check#6]
Can somebody please publish v1.0.2 with this dependency change? 1b91dbb8aa2552addacb7ae98dde7cb7a258594d

Right now I'm getting `Problem in dependency elm-community/elm-check 1.0.1` when I try to package with v1.0.1

**Comment by mgold** [comment]
This was because of elm-community/elm-lazy-list#3. Blow away your `elm-stuff`, reinstall, see if that fixes it.

**Comment by robertjlooby** [comment]
I think it's some weirdness related to the random-extra/elm-random-extra switch. I was using the random-extra package in my test project since the elm-random-extra package said it was deprecated.

With `"elm-community/random-extra": "1.0.0 <= v < 2.0.0"` I can `elm package install` fine, but then when I try to `make` I get the error I mentioned above (I was wrong above, it's when I `make` not `package`).

If I switch to `"elm-community/elm-random-extra": "1.0.0 <= v < 2.0.0"` (and change the places where I'm using the random extra package in my test project) then it works fine.

I can just keep using elm-random-extra until the next release. Thanks!

**Comment by mgold** [comment]
Ok - I completely missed that I had tagged the revision and not published it. Try it now.

**Comment by robertjlooby** [comment]
All good now! Thanks! 👍
